# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/18999/Documents/PG work/BuanGu_230825701_ICDLab2024/Prime_Checker_mod1/Prime_Checker.cache/wt} [current_project]
set_property parent.project_path {C:/Users/18999/Documents/PG work/BuanGu_230825701_ICDLab2024/Prime_Checker_mod1/Prime_Checker.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_vhdl -library xil_defaultlib {{C:/Users/18999/Documents/PG work/BuanGu_230825701_ICDLab2024/Prime_Checker_mod1/Prime_Checker.srcs/sources_1/new/PrimeChecker.vhd}}
read_xdc {{C:/Users/18999/Documents/PG work/BuanGu_230825701_ICDLab2024/Prime_Checker_mod1/Prime_Checker.srcs/constrs_1/imports/Lab guides-20240303/DSDB_Master.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/18999/Documents/PG work/BuanGu_230825701_ICDLab2024/Prime_Checker_mod1/Prime_Checker.srcs/constrs_1/imports/Lab guides-20240303/DSDB_Master.xdc}}]

synth_design -top PrimeChecker -part xc7z020clg484-1
write_checkpoint -noxdef PrimeChecker.dcp
catch { report_utilization -file PrimeChecker_utilization_synth.rpt -pb PrimeChecker_utilization_synth.pb }
